### ISSUE TITLE
GPU id is -1 when using single node fine-tuning

### ISSUE THREAD

**Issue by boyiwei** [ruipeterpan/cos598d_sp24#1]
For single node fine-tuning, args.local_rank defaluts to -1. However, if we want to do single node fine-tuning on GPU, the cuda id will be set to args.local_rank, which is -1.
https://github.com/ruipeterpan/cos598d_sp24/blob/main/run_glue_skeleton.py#L357
CUDA devices are typically referenced using cuda followed by the index of the GPU, starting from 0, if I don't remember wrong. Setting device as cuda:-1 raises error in my device. Not sure whether it is a bug.

**Comment by ruipeterpan** [comment]
Oops, thanks for the catch! Should be fixed now, let me know if it doesn't work.
